services:
  nginx:
    image: nginx:alpine
    volumes:
      - '.:/var/www/html'
      - './docker/local/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pkk-jogja.rule=Host(`pkk.localhost`)"
      - "traefik.http.routers.pkk-jogja.entrypoints=web"
      - "traefik.http.services.pkk-jogja.loadbalancer.server.port=80"
    networks:
      - internal
      - traefik-public
    depends_on:
      - laravel

  laravel:
    build:
      context: ./docker/local/web
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: pkk-jogja/app
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - '.:/var/www/html'
    networks:
      - internal
    depends_on:
      - pgsql

  pgsql:
    image: 'postgres:17'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pkk-jogja-pgsql:/var/lib/postgresql/data'
      - './docker/local/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

volumes:
  pkk-jogja-pgsql:
    driver: local

networks:
  internal:
    driver: bridge
  traefik-public:
    external: true
